# Generated by Django 3.1.3 on 2020-11-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201117_0115'),
    ]

    def create_users(apps, schema_editor):
        """Create default users"""
        User = apps.get_model("core", "User")
        staff_user = User(
            name='Nora', email='Nora@cornershop.com', is_staff=True)

        employee_user = User(
            name='Alejandro', email='Alejandro@cornershop.com')

        staff_user.set_password('password123')
        employee_user.set_password('password123')

        staff_user.save()
        employee_user.save()

    operations = [
        migrations.RunPython(create_users),
    ]
